# Generated by Django 3.1.2 on 2022-10-27 10:51

from django.db import migrations, models
import music_week_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Действует с:')),
                ('image', models.ImageField(default=None, upload_to=music_week_app.models.get_image_name_without_slug, verbose_name='Изображение 1280х904')),
            ],
            options={
                'verbose_name': 'Музыкальная неделя',
                'verbose_name_plural': 'Музыкальные недели',
            },
        ),
    ]
