# Generated by Django 3.1.2 on 2025-02-18 04:53

import baseapp.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Slug')),
                ('images', models.ImageField(upload_to=baseapp.services.get_image_name_by_slug, verbose_name='Изображение 1414x2000')),
            ],
        ),
    ]
