# Generated by Django 3.1.2 on 2025-02-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'verbose_name': 'Меню завтраков', 'verbose_name_plural': 'Меню завтраков'},
        ),
        migrations.RenameField(
            model_name='breakfast',
            old_name='images',
            new_name='image',
        ),
    ]
