# Generated by Django 3.1.2 on 2025-02-18 10:19

import baseapp.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Slug')),
                ('page1', models.ImageField(upload_to=baseapp.services.get_image_name_by_slug, verbose_name='Страница 1 1414x2000')),
                ('page2', models.ImageField(upload_to=baseapp.services.get_image_name_by_slug, verbose_name='Страница 2 1414x2000')),
            ],
            options={
                'verbose_name': 'Барное меню',
                'verbose_name_plural': 'Барное меню',
            },
        ),
    ]
