# Generated by Django 3.0.5 on 2020-08-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodapp', '0043_auto_20200724_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.Properties', verbose_name='Фильтр по свойствам')),
            ],
        ),
    ]
