# Generated by Django 3.1.2 on 2023-03-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertiesfilter',
            options={'verbose_name': 'Фильтр по свойствам', 'verbose_name_plural': 'Фильтры по свойствам'},
        ),
    ]
