# Generated by Django 3.1.2 on 2023-03-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0053_auto_20230313_1453'),
        ('filterapp', '0002_auto_20230313_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesfilter',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodapp.category', verbose_name='Категория'),
        ),
    ]
