# Generated by Django 3.1.2 on 2021-11-25 09:39

from django.db import migrations, models
import festapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('menu_img', models.ImageField(blank=True, default=None, null=True, upload_to=festapp.models.get_image_name, verbose_name='Изображение')),
                ('list_img', models.ImageField(blank=True, default=None, null=True, upload_to=festapp.models.get_image_name, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фестиваль',
                'verbose_name_plural': 'Фестивали',
            },
        ),
    ]
