# Generated by Django 3.1.2 on 2021-11-25 10:18

from django.db import migrations, models
import festapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет согласно HEX, с решеткой'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='list_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=festapp.models.get_image_name, verbose_name='Изображение баннера'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='menu_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=festapp.models.get_image_name, verbose_name='Изображение меню'),
        ),
    ]
