# Generated by Django 3.1.2 on 2022-01-24 14:22

from django.db import migrations, models
import festapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0002_auto_20211125_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='list_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=festapp.models.get_image_name, verbose_name='Изображение баннера 780x411'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='menu_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=festapp.models.get_image_name, verbose_name='Изображение меню 1545x2000'),
        ),
    ]
