# Generated by Django 3.1.2 on 2022-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0003_auto_20220124_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='music_week',
            field=models.BooleanField(default=False, verbose_name='Музыкальные недели'),
        ),
    ]
