# Generated by Django 3.1.2 on 2022-10-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0004_festival_music_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='music_week',
        ),
    ]
