# Generated by Django 3.2.25 on 2025-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0005_remove_festival_music_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
