# Generated by Django 3.1.2 on 2025-03-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0006_alter_festival_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
