# Generated by Django 3.0.5 on 2020-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200610_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='apartments',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Кв.'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='house',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Нас. пункт'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='street',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Улица'),
        ),
    ]
