# Generated by Django 3.0.5 on 2020-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200610_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='porch',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Подъезд'),
        ),
    ]
