# Generated by Django 3.0.5 on 2020-06-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200616_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.CharField(blank=True, max_length=30, verbose_name='Email'),
        ),
    ]
