# Generated by Django 3.0.5 on 2020-04-13 13:19

from django.db import migrations, models
import django.db.models.deletion
import goodapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('name_en', models.CharField(max_length=150, verbose_name='Наименование на английском')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Описание')),
                ('meta_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Старая цена')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Остаток')),
                ('good_uid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Код')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to=goodapp.models.get_image_name, verbose_name='Изображение 550x685')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.Good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
