# Generated by Django 3.0.5 on 2020-04-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0002_properties_property_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='good',
        ),
    ]
