# Generated by Django 3.0.5 on 2020-04-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0012_auto_20200414_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object_property_values',
            unique_together={('good', '_property')},
        ),
    ]
