# Generated by Django 3.0.5 on 2020-04-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0013_auto_20200414_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodapp.Good', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_category',
            field=models.BooleanField(default=False, verbose_name='Это категория'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование на английском'),
        ),
    ]
