# Generated by Django 3.0.5 on 2020-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0014_auto_20200415_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_manufacturer',
            field=models.BooleanField(default=False, verbose_name='Это производитель'),
        ),
    ]
