# Generated by Django 3.0.5 on 2020-04-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0015_good_is_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='proizvoditel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='goodapp.Good', verbose_name='Производитель'),
        ),
    ]
