# Generated by Django 3.0.5 on 2020-04-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0016_good_proizvoditel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog', to='goodapp.Good', verbose_name='Категория'),
        ),
    ]
