# Generated by Django 3.0.5 on 2020-04-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0017_auto_20200415_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='is_manufacturer',
        ),
        migrations.RemoveField(
            model_name='good',
            name='proizvoditel',
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodapp.Good', verbose_name='Категория'),
        ),
    ]
