# Generated by Django 3.0.5 on 2020-04-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0018_auto_20200415_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creat', to='goodapp.Good', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='goodapp.Good', verbose_name='Категория'),
        ),
    ]
