# Generated by Django 3.0.5 on 2020-04-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0020_good_is_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='creator',
        ),
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manuf', to='goodapp.Good', verbose_name='Производитель'),
        ),
    ]
