# Generated by Django 3.0.5 on 2020-04-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0025_auto_20200415_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.RemoveField(
            model_name='good',
            name='is_category',
        ),
    ]
