# Generated by Django 3.0.5 on 2020-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0030_auto_20200415_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Описание'),
        ),
    ]
