# Generated by Django 3.0.5 on 2020-04-21 15:46

from django.db import migrations, models
import goodapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0033_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=goodapp.models.get_image_name, verbose_name='Изображение 370x334'),
        ),
    ]
