# Generated by Django 3.0.5 on 2020-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0034_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Вес'),
        ),
    ]
