# Generated by Django 3.0.5 on 2020-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0036_category_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Вес'),
        ),
    ]
