# Generated by Django 3.0.5 on 2020-05-15 04:25

from django.db import migrations, models
import goodapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0039_auto_20200514_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='images',
            field=models.ImageField(default=None, upload_to=goodapp.models.get_image_name, verbose_name='Изображение 550x685'),
        ),
    ]
