# Generated by Django 3.0.5 on 2020-06-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0040_auto_20200515_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_Barrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.Good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Сидр в бочках',
                'verbose_name_plural': 'Сидры в бочках',
            },
        ),
    ]
