# Generated by Django 3.0.5 on 2020-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0041_in_barrels'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='in_barrel',
            field=models.BooleanField(default=False, verbose_name='Розлив'),
        ),
    ]
