# Generated by Django 3.0.5 on 2020-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0042_good_in_barrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cpu_slug',
            field=models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url'),
        ),
        migrations.AddField(
            model_name='good',
            name='cpu_slug',
            field=models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='cpu_slug',
            field=models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url'),
        ),
    ]
