# Generated by Django 3.0.5 on 2020-09-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0043_auto_20200724_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='upsell_products',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goodapp.Good', verbose_name='Рекомендумые товары'),
        ),
    ]
