# Generated by Django 3.0.5 on 2020-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0044_good_upsell_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='upsell_products',
        ),
        migrations.AddField(
            model_name='good',
            name='upsell_products',
            field=models.ManyToManyField(to='goodapp.Good'),
        ),
    ]
