# Generated by Django 3.0.5 on 2020-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0045_auto_20200914_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='upsell_products',
            field=models.ManyToManyField(blank=True, to='goodapp.Good', verbose_name='Рекомендуемые товары'),
        ),
    ]
