# Generated by Django 3.0.5 on 2020-10-08 09:21

from django.db import migrations, models
import goodapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0046_auto_20200930_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('date', models.DateField()),
                ('image', models.ImageField(default=None, upload_to=goodapp.models.get_image_name, verbose_name='Изображение 550x685')),
            ],
            options={
                'verbose_name': 'Комплексный обед',
                'verbose_name_plural': 'Комплексные обеды',
            },
        ),
    ]
