# Generated by Django 3.1.2 on 2020-10-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0048_auto_20201009_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_cidre',
            field=models.BooleanField(default=False, verbose_name='Сидр'),
        ),
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Хит продаж',
                'verbose_name_plural': 'Хиты продаж',
            },
        ),
    ]
