# Generated by Django 3.1.2 on 2020-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0049_auto_20201023_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование'),
        ),
    ]
