# Generated by Django 3.1.2 on 2023-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0050_bestseller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_vine',
            field=models.BooleanField(default=False, verbose_name='Вино'),
        ),
    ]
