# Generated by Django 3.1.2 on 2023-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0051_good_is_vine'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='color',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='good',
            name='fragrance',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='Аромат'),
        ),
        migrations.AddField(
            model_name='good',
            name='taste',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='Вкус'),
        ),
    ]
