# Generated by Django 3.1.2 on 2023-03-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0052_auto_20230313_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object_property_values',
            unique_together=set(),
        ),
    ]
