# Generated by Django 3.1.2 on 2023-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0053_auto_20230313_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='display_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование для отображения'),
        ),
    ]
