# Generated by Django 3.1.2 on 2024-11-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0054_properties_display_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Third_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.good', verbose_name='Товар')),
                ('set_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_lunch', verbose_name='Комплексный обед')),
            ],
            options={
                'verbose_name': 'Третье блюдо',
                'verbose_name_plural': 'Третьи блюда',
            },
        ),
        migrations.CreateModel(
            name='Second_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.good', verbose_name='Товар')),
                ('set_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_lunch', verbose_name='Комплексный обед')),
            ],
            options={
                'verbose_name': 'Второе блюдо',
                'verbose_name_plural': 'Вторые блюда',
            },
        ),
        migrations.CreateModel(
            name='First_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.good', verbose_name='Товар')),
                ('set_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_lunch', verbose_name='Комплексный обед')),
            ],
            options={
                'verbose_name': 'Первое блюдо',
                'verbose_name_plural': 'Первые блюда',
            },
        ),
    ]
