# Generated by Django 3.1.2 on 2024-12-03 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodapp', '0054_properties_display_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGood',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Наименование на английском')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('gastronomy', models.TextField(blank=True, default='', max_length=512, verbose_name='Гастрономия')),
                ('color', models.TextField(blank=True, default='', max_length=512, verbose_name='Цвет')),
                ('fragrance', models.TextField(blank=True, default='', max_length=512, verbose_name='Аромат')),
                ('taste', models.TextField(blank=True, default='', max_length=512, verbose_name='Вкус')),
                ('meta_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Старая цена')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_cidre', models.BooleanField(default=False, verbose_name='Сидр')),
                ('is_vine', models.BooleanField(default=False, verbose_name='Вино')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Остаток')),
                ('weight', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Вес')),
                ('good_uid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Код')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('in_barrel', models.BooleanField(default=False, verbose_name='Розлив')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='goodapp.category', verbose_name='Категория')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='goodapp.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'historical Товар',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
