# Generated by Django 3.1.2 on 2024-11-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0055_first_course_second_course_third_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_course',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodapp.good', verbose_name='Товар'),
        ),
    ]
