# Generated by Django 3.1.2 on 2024-12-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0055_historicalgood'),
        ('goodapp', '0056_auto_20241125_1438'),
    ]

    operations = [
    ]
