# Generated by Django 3.1.2 on 2024-12-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0057_merge_20241204_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Комплексный обед',
                'verbose_name_plural': 'Комплексные обеды',
            },
        ),
        migrations.RemoveField(
            model_name='first_course',
            name='set_lunch',
        ),
        migrations.RemoveField(
            model_name='second_course',
            name='set_lunch',
        ),
        migrations.RemoveField(
            model_name='third_course',
            name='set_lunch',
        ),
        migrations.AddField(
            model_name='first_course',
            name='set_meal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_meal', verbose_name='Комплексный обед'),
        ),
        migrations.AddField(
            model_name='second_course',
            name='set_meal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_meal', verbose_name='Комплексный обед'),
        ),
        migrations.AddField(
            model_name='third_course',
            name='set_meal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_meal', verbose_name='Комплексный обед'),
        ),
    ]
