# Generated by Django 3.1.2 on 2024-12-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0060_auto_20241204_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_course',
            name='set_meal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_meal', verbose_name='Комплексный обед'),
        ),
        migrations.AlterField(
            model_name='second_course',
            name='set_meal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_meal', verbose_name='Комплексный обед'),
        ),
        migrations.AlterField(
            model_name='third_course',
            name='set_meal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodapp.set_meal', verbose_name='Комплексный обед'),
        ),
    ]
