# Generated by Django 3.1.2 on 2024-12-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0061_auto_20241204_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='second_course',
            name='good',
        ),
        migrations.RemoveField(
            model_name='second_course',
            name='set_meal',
        ),
        migrations.RemoveField(
            model_name='third_course',
            name='good',
        ),
        migrations.RemoveField(
            model_name='third_course',
            name='set_meal',
        ),
        migrations.DeleteModel(
            name='First_Course',
        ),
        migrations.DeleteModel(
            name='Second_Course',
        ),
        migrations.DeleteModel(
            name='Third_Course',
        ),
    ]
