# Generated by Django 3.1.2 on 2024-12-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0062_auto_20241204_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set_meal',
            options={'verbose_name': 'Комплексный обед с товарами', 'verbose_name_plural': 'Комплексные обеды с товарами'},
        ),
    ]
