# Generated by Django 3.1.2 on 2024-12-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0064_first_course_second_course_third_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_course',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='second_course',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='third_course',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
