# Generated by Django 3.1.2 on 2026-05-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0068_historicalcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='second_course',
            name='good',
        ),
        migrations.RemoveField(
            model_name='second_course',
            name='set_meal',
        ),
        migrations.RemoveField(
            model_name='third_course',
            name='good',
        ),
        migrations.RemoveField(
            model_name='third_course',
            name='set_meal',
        ),
        migrations.DeleteModel(
            name='First_Course',
        ),
        migrations.DeleteModel(
            name='Second_Course',
        ),
        migrations.DeleteModel(
            name='Set_Meal',
        ),
        migrations.DeleteModel(
            name='Third_Course',
        ),
    ]
