# Generated by Django 3.0.5 on 2020-06-08 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 8, 12, 27, 12, 85445, tzinfo=utc), verbose_name='Дата заказа'),
            preserve_default=False,
        ),
    ]
