# Generated by Django 3.0.5 on 2020-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
