# Generated by Django 3.1.2 on 2026-04-28 08:51

import baseapp.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_set_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, upload_to=baseapp.services.get_image_name_by_slug, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='LunchSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('dishType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_set_app.dishestype', verbose_name='Тип блюда')),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_set_app.dish', verbose_name='Блюдо')),
            ],
        ),
    ]
