# Generated by Django 3.1.2 on 2026-04-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_set_app', '0002_auto_20260428_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchset',
            name='dishType',
        ),
        migrations.RemoveField(
            model_name='lunchset',
            name='dishes',
        ),
    ]
