# Generated by Django 3.1.2 on 2026-04-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_set_app', '0003_auto_20260428_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectForSetLunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_set_app.dish', verbose_name='Блюдо')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_set_app.dishestype', verbose_name='Тип блюда')),
                ('lunch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_set_app.lunchset', verbose_name='Комплексный обед')),
            ],
        ),
    ]
