# Generated by Django 3.1.2 on 2026-05-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_set_app', '0004_objectforsetlunch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishestype',
            options={'verbose_name': 'Тип блюда', 'verbose_name_plural': 'Типы блюд'},
        ),
        migrations.AlterModelOptions(
            name='lunchset',
            options={'verbose_name': 'Комплексный обед', 'verbose_name_plural': 'Комплексные обеды'},
        ),
    ]
